---
- name: Create S3 storage on Ceph
  hosts: all
  become: yes
  any_errors_fatal: true 
  roles:
    - ceph_hosts
    - passwordless
    - bootstrap-master
    - prepare_node
    - ssh-keys
    - add_hosts
    - add_osds
    - create_rgw
    - add_s3user