---
- name: Create S3 storage on Ceph
  hosts: all
  become: yes
  any_errors_fatal: true 
  roles:
    - ceph_hosts
    - passwordless
    - prepare_node_new
    - ssh-keys
    - add_hosts
    - add_osds