seaweed_dir: /opt/seaweedfs
seaweed_data_dir: /opt/seaweedfs/data


master_port: 9333
replication: 001

volume_port: 8080
filer_port: 8888
s3_port: 8333

seaweed_s3_filer_host: 127.0.0.1

volume_max: 10

nginx_s3_domain: "{{ ansible_host }}"

nginx_s3_backends: >-
  {{ groups['s3']
     | map('extract', hostvars, 'ansible_host')
     | map('regex_replace', '$', ':' ~ s3_port)
     | list }}

s3_admin_user: admin
s3_access_key: admin
s3_secret_key: secretkey
s3_actions: "Admin,Read,Write,List,Tagging"
s3_credentials_output_dir: "{{ playbook_dir }}/output"