---
# 1. Сначала забираем ключ с мастера (выполняется 1 раз, данные сохраняются в памяти мастера)
- name: Fetch dynamic Ceph Orchestrator public key from master
  slurp:
    src: /etc/ceph/ceph.pub
  register: ceph_key_data
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

# 2. Раздаем ключи только воркерам
- name: Add Node-Master and Ceph keys to workers
  block:
    - name: Add Node-Master standard public key
      authorized_key:
        user: "{{ ceph_ssh_user }}"
        key: "{{ node_master_ssh_key }}"
        state: present

    - name: Add Ceph Orchestrator dynamic public key
      authorized_key:
        user: "{{ ceph_ssh_user }}"
        # Обращаемся к фактам мастер-ноды
        key: "{{ hostvars[groups['master'][0]]['ceph_key_data']['content'] | b64decode }}"
        state: present
  when: inventory_hostname in groups['workers']
  become: true