- name: Add S3 user
  block:
    - name: Check if RGW user exists
      ansible.builtin.command: >
        radosgw-admin user info --uid={{ rgw_user_uid }}
      register: rgw_user_info
      failed_when: false
      changed_when: false
      timeout: 30
      environment:
        CEPH_CONF: /etc/ceph/ceph.conf

    # Если пользователь существует — парсим JSON
    - name: Parse existing RGW user info
      ansible.builtin.set_fact:
        rgw_user_existing: "{{ rgw_user_info.stdout | from_json }}"
      when: rgw_user_info.rc == 0

    # Создание пользователя
    - name: Create RGW user
      ansible.builtin.command: >
        radosgw-admin user create
        --uid={{ rgw_user_uid }}
        --display-name="{{ rgw_user_display_name }}"
      register: rgw_user_create
      changed_when: true
      timeout: 30
      environment:
        CEPH_CONF: /etc/ceph/ceph.conf
      when: rgw_user_info.rc != 0

    # Обновление display-name (если изменился)
    - name: Update RGW user display name
      ansible.builtin.command: >
        radosgw-admin user modify
        --uid={{ rgw_user_uid }}
        --display-name="{{ rgw_user_display_name }}"
      register: rgw_user_modify
      changed_when: true
      timeout: 30
      environment:
        CEPH_CONF: /etc/ceph/ceph.conf
      when:
        - rgw_user_info.rc == 0
        - rgw_user_existing.display_name != rgw_user_display_name

    # Формируем единую переменную с данными пользователя
    - name: Set RGW user data for file
      ansible.builtin.set_fact:
        rgw_user_data: >-
          {{
            (rgw_user_create.stdout | from_json)
            if (rgw_user_create is defined and 'stdout' in rgw_user_create)
            else rgw_user_existing
          }}

    # Сохранить файл на control node (откуда запускается плейбук)
    - name: Ensure local output directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/output"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Save keys to local file
      ansible.builtin.copy:
        content: "{{ rgw_user_data | to_nice_json }}"
        dest: "{{ playbook_dir }}/output/{{ rgw_user_uid }}_keys.json"
        mode: '0666'
      delegate_to: localhost
      when: inventory_hostname in groups['master']


  when: inventory_hostname in groups['master']
  become: true