- name: Install SeaweedFS on all nodes
  hosts: seaweedfs
  become: yes
  any_errors_fatal: true 

  roles:
    - seaweedfs_common
    - seaweedfs_master
    - seaweedfs_volume
    - seaweedfs_filer

- name: Deploy S3 only on first node
  hosts: s3
  become: yes
  any_errors_fatal: true 

  roles:
    - seaweedfs_s3

- name: Deploy nginx
  hosts: loadbalancer
  become: yes
  any_errors_fatal: true 

  roles:
    - nginx
