- name: Remove nginx
  hosts: loadbalancer
  become: yes

  roles:
    - delete_nginx

- name: Remove S3 component
  hosts: s3
  become: yes

  roles:
    - delete_s3

- name: Remove SeaweedFS on all nodes
  hosts: seaweedfs
  become: yes

  roles:
    - delete_seaweedfs
